/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TalameedRouteImport } from './routes/talameed'
import { Route as TaleemRouteImport } from './routes/taleem'
import { Route as ApiPublicNotifySubmissionRouteImport } from './routes/api/public/notify-submission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TalameedRoute = TalameedRouteImport.update({
  id: '/talameed',
  path: '/talameed',
  getParentRoute: () => rootRouteImport,
} as any)
const TaleemRoute = TaleemRouteImport.update({
  id: '/taleem',
  path: '/taleem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifySubmissionRoute =
  ApiPublicNotifySubmissionRouteImport.update({
    id: '/api/public/notify-submission',
    path: '/api/public/notify-submission',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/talameed': typeof TalameedRoute
  '/taleem': typeof TaleemRoute
  '/api/public/notify-submission': typeof ApiPublicNotifySubmissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/talameed': typeof TalameedRoute
  '/taleem': typeof TaleemRoute
  '/api/public/notify-submission': typeof ApiPublicNotifySubmissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/talameed': typeof TalameedRoute
  '/taleem': typeof TaleemRoute
  '/api/public/notify-submission': typeof ApiPublicNotifySubmissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/reset-password'
    | '/talameed'
    | '/taleem'
    | '/api/public/notify-submission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/reset-password'
    | '/talameed'
    | '/taleem'
    | '/api/public/notify-submission'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/reset-password'
    | '/talameed'
    | '/taleem'
    | '/api/public/notify-submission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TalameedRoute: typeof TalameedRoute
  TaleemRoute: typeof TaleemRoute
  ApiPublicNotifySubmissionRoute: typeof ApiPublicNotifySubmissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talameed': {
      id: '/talameed'
      path: '/talameed'
      fullPath: '/talameed'
      preLoaderRoute: typeof TalameedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taleem': {
      id: '/taleem'
      path: '/taleem'
      fullPath: '/taleem'
      preLoaderRoute: typeof TaleemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-submission': {
      id: '/api/public/notify-submission'
      path: '/api/public/notify-submission'
      fullPath: '/api/public/notify-submission'
      preLoaderRoute: typeof ApiPublicNotifySubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TalameedRoute: TalameedRoute,
  TaleemRoute: TaleemRoute,
  ApiPublicNotifySubmissionRoute: ApiPublicNotifySubmissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
